apiVersion: ref.nephio.org/v1alpha1
kind: Config
metadata:
  name: amf-regional-gnb-edge01
  namespace: example
spec:
  config:
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment
    metadata:
      name: amf-regional
      namespace: oaicp
    spec:
      provider: amf.openairinterface.org
      capacity:
        maxDownlinkThroughput: "0"
        maxSubscribers: 64
        maxUplinkThroughput: "0"
      interfaces:
      - name: n2
        ipv4:
          address: 172.21.6.94/24
          gateway: 172.21.6.94
        vlanID: 4
      networkInstances:
      - name: vpc-ran
        interfaces:
        - n2
