apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: replace-namespace
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: kptfile.kpt.dev
    fieldPath: data.name
  targets:
  - select:
      kind: Config
    fieldPaths:
    - metadata.namespace
  - select:
      kind: NFDeployment
    fieldPaths:
    - spec.configRefs.[kind=Config].namespace
  - select:
      kind: Interface
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/namespace]
  - select:
      kind: Capacity
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/namespace]
  - select:
      kind: DataNetwork
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/namespace]
  - select:
      kind: Dependency
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/namespace]