apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: # kpt-merge: /set-annotation
  name: set-configuration-du
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: fn.kpt.dev|StarlarkRun|default|set-configuration
source: |-
  append_flag = False
  for resource in ctx.resource_list["items"]:
    if resource.get("kind") == "Kptfile" and resource.get("status") != None:
      for status in resource["status"]["conditions"]:
        if "NFDeployment" in status["type"] and status["status"] == "True":
          append_flag = True
  
  if append_flag == True:
    for resource in ctx.resource_list["items"]:
      if resource.get("kind") == "NFDeployment" and resource.get("spec") != None:
        if resource["spec"].get("parametersRefs") != None:          
            resource["spec"]["parametersRefs"].append({"name": "du-nf-config-edge01",
                                                    "apiVersion": "workload.nephio.org/v1alpha1", 
                                                    "kind": "NFConfig"
                                                    })
        else:
          resource["spec"]["parametersRefs"] = [{"name": "du-nf-config-edge01",
                                                    "apiVersion": "workload.nephio.org/v1alpha1", 
                                                    "kind": "NFConfig"
                                                    }]