apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: f1
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.du-example
    specializer.nephio.org/namespace: example
spec:
  networkInstance:
    name: vpc-internal
  cniType: macvlan
  attachmentType: vlan