apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-crds
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: nephio-workload-crds
    repo: nephio-workload-crds
    revision: main
  downstream:
    package: example-crds
    repo: mgmt-staging
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example
