apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: 
  name: cuup-example
  namespace: example
spec:
  provider: cuup.openairinterface.org
  capacity:
    maxDownlinkThroughput: 100M
    maxUplinkThroughput: 1M
  parametersRefs:
    - apiVersion: workload.nephio.org/v1alpha1
      kind: NFConfig
      name: cuup-nf-config-edge01