apiVersion: req.nephio.org/v1alpha1
kind: Interface
metadata:
  name: ue-rfsim
  annotations:
    nephio.org/network-name: ue-rfsim
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: apps/v1.Deployment.oai-nr-ue
    specializer.nephio.org/namespace: oai-ue
spec:
  networkInstance:
    name: vpc-ue-rfsim
  cniType: macvlan
  attachmentType: vlan