apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: regional-oai-cucp
spec:
  upstream:
    repo: catalog
    package: pkg-example-cucp-bp
    revision: v1
  downstream:
    repo: regional
    package: oai-ran-cucp
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: regional
