apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge-oai-cucp
spec:
  upstream:
    repo: oai-ran-packages
    package: pkg-example-cucp-bp
    revision: v1
  downstream:
    repo: edge01
    package: oai-ran-cucp
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: edge01
